version: "3.7"
services:
  postgres:
    container_name: go-postgres
    restart: always
    image: postgres:17.2
    environment:
      - POSTGRES_DB=go-db
      - POSTGRES_USER=go
      - POSTGRES_PASSWORD=go
      - PGDATA=/var/lib/postgresql/data/go-pg-data
    volumes:
      - go-pg-data:/var/lib/postgresql/data/go-pg-data
    ports:
      - "5439:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

volumes:
  go-pg-data:
